### ISSUE TITLE
Creates a whole lot of null pointer errors

### ISSUE THREAD

**Issue by Pajn** [willothy/savior.nvim#3]
I'm getting a whole lot of errors like:
```
Error executing vim.schedule lua callback: ...rasmus/.local/share/nvim/lazy/savior.nvim/lua/savior.lua:47: attempt to index field 'progress' (a nil value)
stack traceback:
        ...rasmus/.local/share/nvim/lazy/savior.nvim/lua/savior.lua:47: in function 'progress_start'
        ...rasmus/.local/share/nvim/lazy/savior.nvim/lua/savior.lua:105: in function 'cb'
        ...rasmus/.local/share/nvim/lazy/savior.nvim/lua/savior.lua:220: in function 'callback'
        ...rasmus/.local/share/nvim/lazy/savior.nvim/lua/savior.lua:258: in function 'fn'
        ...rasmus/.local/share/nvim/lazy/savior.nvim/lua/savior.lua:187: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

Looking at the code, it seems like this line https://github.com/willothy/savior.nvim/blob/main/lua/savior.lua#L44 should instead be `if not progress[bufnr] then`, protecting against the nil case.

**Comment by willothy** [comment]
That line is just ensuring that we don't create multiple progress handles for a buffer, so isn't the cause of this and shouldn't be negated, but I appreciate the suggestion :)

I will look into this ASAP, but could you provide a minimal init and/or steps to reproduce? I have never experienced this.

**Comment by Pajn** [comment]
I see, I read that incorrectly. I'll see if I can debug it a bit better tomorrow.

**Comment by willothy** [comment]
No worries, thanks!

**Comment by Pajn** [comment]
I have been using it all day today without any errors. Not really sure what changed, yesterday I just renamed the file confguring it to `.bak` to stop the errors and today I dropped that suffix again.
Don't know if the lazy installation got corrupted somehow the first time?

Anyway, I'll close this and reopen if I see it again and can find a way to reproduce it.
Super big thanks for the plugin and sorry to bother you!

**Comment by willothy** [comment]
No worries at all! I'll still look into it and see if I can find the cause.

Glad you like the plugin, I mainly made this one for myself so I'm glad some other people are finding it useful :)

**Comment by willothy** [comment]
Looking at the error again, it looks like you might have had an outdated version of fidget.nvim installed.

**Comment by Pajn** [comment]
Was actually about to write a similar thought. Pulling my dotfiles on another computer got the same issue, but after a lazy sync it fixed itself.

**Comment by willothy** [comment]
Glad it's all good now! Let me know if there's any other issues you run into.
