### ISSUE TITLE
Is there `timeout` variable?

### ISSUE THREAD

**Issue by azzamsa** [willothy/savior.nvim#5]
Hi 👋

Is there a `timeout` variable?
I don't want the notification to stay longer than `n` seconds.
Or, I don't want the notification at all.
Because sometimes it covers my content.

Coming from Emacs, I am struggling to find a `super-save` alternative.
Thank you for savior! 🍦

**Comment by willothy** [comment]
The timeout of notifications is handled by fidget.nvim. I can add an option to disable it entirely though, if you'd like that :)

**Comment by azzamsa** [comment]
> can add an option to disable it entirely though, if you'd like that :)

That would be a nice feature! 👍🏽

**Comment by willothy** [comment]
Added in 4ecbdbb!

**Comment by azzamsa** [comment]
@willothy wow, thank you so much 🍦 

Would you like to use `stable` tags? such https://github.com/stevearc/oil.nvim/tags
So we don't need to change the version tag or commit hash in our nvim config. (Yes, I hard-coded them to avoid miss-upgrading to  bleeding edge version)

**Comment by willothy** [comment]
If you want to keep up to date with the latest changes, you can just remove the version specifier or pin the main branch. I'll consider it but I would have to setup automation and I don't quite see a reason for it...

**Comment by azzamsa** [comment]
> If you want to keep up to date with the latest changes, you can just remove the version specifier or pin the main branch. I'll consider it but I would have to setup automation and I don't quite see a reason for it...

Oh, I see.

![image](https://github.com/willothy/savior.nvim/assets/17734314/759b330f-4999-498f-8ef7-befcdc11fe58)

Now I get this error.

```lua
    {
        "willothy/savior.nvim",
        commit = "658dd8f169a5c0ed05d2c270d36fcaa87b685a3d",
        dependencies = { "j-hui/fidget.nvim", version = "1.3.0" },
        event = { "InsertEnter", "TextChanged" },
        config = function()
            local savior = require("savior")
            savior.setup({
                -- Set to false to disable fidget.nvim notifications
                notify = false,
            })
        end,
    },
```

**Comment by willothy** [comment]
Oops, I guess you're not using nvim 0.10. I'll remove the iter usage.

**Comment by azzamsa** [comment]
Worked like a charm! 🍨 
Thank you so much.
